---
- name: install docker
  hosts: all
  become: yes
  tasks:
    - apt:
        name: docker.io
        state: present 
    - apt:
        name: python-pip
        state: present
    - pip:
        name: docker-py
- name: build java
  hosts: bld 
  become: yes
  tasks: 
    - name: clone from git
      git:
        repo: 'https://github.com/cherukuriPraveenchowdary/Sample-Java-War.git'
        dest: /tmp/java
        clone: yes
    - name: Start a container with a command
      docker_container:
        name: mvn
        command: --rm -v /tmp/java:/opt/maven -w /opt/maven maven:3.3.9-jdk-8 mvn package
- name: copy file from bld to serv
  hosts: bld
  tasks:
    - fetch:
        src: /tmp/java/target/
        dest: ./java/
        flat: true
- name: copy file from serv to web
  hosts: web
  tasks:
    - copy:
        src: ./java
        dest: /tmp/java
- name: web server
  hosts: web
  become: yes
  tasks:
    - name: Container present
      docker_container:
        name: tomcat 
        state: present
        image: tomcat:9
        ports: "8080:8080"
        volumes:
        - /tmp/java:/usr/local/tomcat/webapps
        